image:
  name: ribose/metanorma
  entrypoint: [""]

cache:
  paths:

build:
  stage: build
  script:
    - bundle
    - make clean all publish
    - mv published public
  artifacts:
    paths:
      - public
