= CalConnect/ISO 24229: Information and documentation -- Codes for script conversion systems

This work item belongs to ISO/TC 46/WG 3 and CalConnect TC LOCALIZATION.

image:https://github.com/CalConnect/csd-transcription-systems/actions/workflows/publish.yml/badge.svg["Publish", link="https://github.com/CalConnect/csd-transcription-systems/actions/workflows/publish.yml"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-transcription-systems/[(GitHub) CC/ISO 24229: Information and documentation -- Codes for script conversion systems]

* https://calconnect.gitlab.io/tc-localization/csd-transcription-systems/[(GitLab, deprecated) CC/ISO 24229: Information and documentation -- Codes for script conversion systems]


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-transcription-systems
----


== Installing Build Tools

[source,sh]
----
make prep
----


== Building The Document

[source,sh]
----
make
----

The following outputs will be built:

* Document index at `documents.html`
* ISO 24229 at `documents/iso-24229.html`
* CC 24229 at `documents/iso-24229.html`
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make
open site/documents/iso-24229.html
open site/documents/cc-24229.html
----


== Updating gems

Update `Gemfile` with desired modifications and run `bundle install`, then check
in `Gemfile.lock`.


=== Updating gems (with Nix)

After updating gems as decribed above, run the following, then check in
the generated `gemset.nix`.

[source,bash]
----
rm -f .bundle/config  # This interferes with the following.  May be unneeded for Bundler v3
nix-shell -p bundix zlib libxml2 pkg-config libxslt libiconv --run 'bundix --magic'
# $(nix-build "<nixpkgs>" -A bundix --no-out-link)/bin/bundix --magic
----

The packages listed are for building nokogiri: `zlib libxml2 pkg-config libxslt libiconv`.
