= CalConnect Standard: Information and documentation -- Codes for transcription systems

This work item belongs to TC LOCALIZATION.

image:https://github.com/CalConnect/csd-transcription-systems/workflows/publish/badge.svg["Build Status", link="https://github.com/CalConnect/csd-transcription-systems/actions?workflow=publish"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-transcription-systems/[CC/ISO: Information and documentation -- Codes for transcription systems]


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-transcription-systems/
----

== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=metanorma/mn
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open cc-*.html
----

