= CalConnect/ISO 24229: Information and documentation -- Codes for script conversion systems

This work item belongs to ISO/TC 46/WG 3 and CalConnect TC LOCALIZATION.

image:https://github.com/CalConnect/csd-transcription-systems/actions/workflows/publish.yml/badge.svg["Publish", link="https://github.com/CalConnect/csd-transcription-systems/actions/workflows/publish.yml"]

This document is available in its rendered forms here:

* https://calconnect.gitlab.io/tc-localization/csd-transcription-systems/[CC/ISO 24229: Information and documentation -- Codes for script conversion systems]


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-transcription-systems
----


== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=metanorma/metanorma
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make
----

The following outputs will be built:

* Document index at `documents.html`
* ISO 24229 at `documents/iso-24229.html`
* CC 24229 at `documents/iso-24229.html`
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make
open documents/iso-24229.html
open documents/cc-24229.html
----
