
'******* CONFIGURATION ************************************************
class ScriptConversionSystemAuthority {
  +authorityCode: String
  +name: String
  +remarks: String
}

'******* CLASS RELATIONS **********************************************

/' 'AuthorityInfo <-- PublicKey '/
