
'******* CONFIGURATION ************************************************
class ScriptConversionSystemAuthority {
  +authorityCode: String
  +uri: Uri
  +name: LocalizedStringCollection
'  +iso3166Code: iso3166Code
  +description: LocalizedStringCollection
}

'******* CLASS RELATIONS **********************************************

'AuthorityInfo <-- PublicKey
