
'******* CONFIGURATION ************************************************
class SCSRelation {
  +systemCode: SystemCode
  +type: SCSRelationType[0..*]
}

enum SCSRelationType {
  aliasOf
  adoptedFrom
  supercedes
  replacedBy
  relatedTo
  basedOn
}

'******* CLASS RELATIONS **********************************************
