
'******* CONFIGURATION ************************************************
class ScriptConversionSystem {
  +code: SystemCode
  +name: String
  +language: iso639Code
  +sourceSpelling: SpellingSystem
  +targetSpelling: SpellingSystem
  +systemIdentifier: String
  +relations: SCSRelation[0..*]
  +status: SCSStatus
  +remarks: String
}

String <|-- SystemCode

'******* CLASS RELATIONS **********************************************
