
'******* CONFIGURATION ************************************************
class ScriptConversionSystem {
  +code: SystemCode
  +name: String
  +language: iso639Code
  +sourceScript: iso15924Code
  +targetScript: iso15924Code
  +systemIdentifier: String
  +relations: SCSRelation[0..*]
  +remarks: String
}

String <|-- SystemCode

'******* CLASS RELATIONS **********************************************
