[[introduction]]

== Introduction

A number of international applications require
the identification of written language conversion systems, including for
terminology, lexicography, bibliography, and linguistics,
especially for reverse transliteration,
computational linguistics and machine pronunciation.

This document sets out the necessary procedures to maintain
the registry of written language conversion systems.


The chosen term "written language conversion" is intended to refer to all types
of conversions, i.e. transformations of written texts from one spelling system
to another.
It thus includes both script conversion (change of script: transliteration,
transcription) and conversion of texts without changing the script
(e.g. transcription of foreign names or words using the alphabet of a target
language, change of the orthography in a language, etc.).
For the sake of compactness of expression, "written language conversion" has
been shortened to "conversion" in this document where it does not
cause ambiguity.
