
[[terms]]
//[source=ISO5127]
== Terms and definitions


=== script

particular graphic representation or class of representations of a set of
characters used to write one or more _languages_ (<<ISO5127,clause="3.1.5.01">>)

[.source]
<<ISO5127,clause="3.1.6.02">>



=== spelling system

set of rules governing the orthography of a language

NOTE: Typically, a spelling system defines how the spoken form of a
language is represented in writing.
Several languages have undergone orthographic reforms which means they have had
different spelling systems.


=== written language

_natural language_ (<<ISO5127,clause=3.1.5.02>>) realized through the writing of _characters_ (<<ISO5127,clause=3.1.4.02>>)

[.source]
<<ISO5127,clause="3.1.5.04">>


=== written languages conversion

process whereby one term:[spelling system] is converted into another spelling system

NOTE: This is a general term that includes script conversion but also,
e.g., cases when a language changes its orthography without changing the script.


=== transliteration

process which consists of representing the characters of an alphabetical or
syllabic system of writing by the characters of a conversion alphabet


=== transcription

process whereby the sounds of a given language are noted by the system of signs
of a conversion language


=== romanization

_script conversion_ (<<ISO5127,clause="3.1.6.13">>) from non-Roman to Roman
term:[script] by means of _transliteration_ (<<ISO5127,clause="3.1.6.11">>),
_transcription (2) activity_ (<<ISO5127,clause="3.1.6.10">>) or both

[.source]
<<ISO5127,clause="3.1.6.14">>


=== written languages conversion system

a set of rules for term:[written languages conversion]


=== language code

combination of characters used to represent the name of a _language_ (<<ISO5127,clause="3.1.5.01">>) or languages

[.source]
<<ISO5127,clause="3.2.5.14">>


=== script code

combination of characters used to represent the name of a term:[script]

[.source]
<<ISO15924,clause="3.8">>


=== conversion system code

combination of characters used in a structured way to represent a
term:[written languages conversion system]


////

=== transliterated text

text output of a transliteration system on a transliteration source

=== transliteration script

script form produced by a transliteration system on the transliteration source


=== source language

language used in the transliteration source

=== source script

script used in the transliteration source

////
