
[[terms]]
//[source=ISO5127]
== Terms and definitions


=== script

particular graphic representation or class of representations of a set of
characters used to write one or more _languages_ (<<ISO5127,clause="3.1.5.01">>)

[.source]
<<ISO5127,clause="3.1.6.02">>




=== spelling system

set of rules governing the orthography of a language

Note to entry: Typically, a spelling system defines how the spoken form of a
language is represented in writing.
Several languages have undergone orthographic reforms which means they have had
different spelling systems.


=== written language

_natural language_ (<<ISO5127,clause=3.1.5.02>>) realized through the writing of _characters_ (<<ISO5127,clause=3.1.4.02>>)

[.source]
<<ISO5127,clause="3.1.5.04">>


=== written languages conversion

process whereby one spelling system is converted into another spelling system

Note to entry: This is a general term that includes script conversion but also,
e.g., cases when a language changes its orthography without changing the script.


=== transliteration

TODO: use a more traditional definition

operation to convert a term:[script] into another script without change of term:[language] based on orthographic features of the source script


// === transcription

// TODO: use a more traditional definition

// operation to convert spoken term:[language] or a term:[script] to another
//script without change of language based on phonetic features of the language
//and orthographic features of the source script


=== romanization

term:[script conversion] from non-Roman to Roman script by means of term:[transliteration], transcription <activity> or both

[.source]
<<ISO5127,clause="3.1.6.14">>


=== written languages conversion system

TODO:

a set of rules for term:[written languages conversion]




=== code

_data_ (<<ISO5127,clause=3.1.13.10>>) transformed or represented in different forms
according to a pre-established _set_ (<<ISO5127,3.1.1.09>>) of rules

////
{{ISO5127,clause=3.1.13.10,data}} transformed or represented in different forms
according to a pre-established {{ISO5127,3.1.1.09,set}} of rules
////

[.source]
<<ISO5127,clause="3.1.13.10">>, Note 1 to entry is omitted.


=== language code

combination of characters used to represent the name of a term:[language] or languages

[.source]
<<ISO5127,clause="3.2.5.14">>


=== script code

combination of characters used to represent the name of a term:[script]

[.source]
<<ISO15924,clause="3.8">>


=== conversion system code

term:[code] used to represent a term:[written languages conversion system]


////

=== transliterated text

text output of a transliteration system on a transliteration source

=== transliteration script

script form produced by a transliteration system on the transliteration source


=== source language

language used in the transliteration source

=== source script

script used in the transliteration source

////
