
[[terms]]
//[source=ISO5127]
== Terms and definitions


=== script

particular graphic representation or class of representations of a set of
characters used to write one or more term:[language, languages]

[.source]
<<ISO5127,clause="3.1.6.02">>


=== language

systematic use of sounds, characters, symbols or signs to express meaning or communicate meaning or a message

[.source]
<<ISO5127,clause="3.1.5.01">>


=== script conversion

term:[transliteration] or term:[transcription]


=== transliteration

operation to convert a term:[script] into another script without change of term:[language] based on orthographic features of the source script


=== transcription

operation to convert spoken term:[language] or a term:[script] to another script without change of language based on phonetic features of the language and orthographic features of the source script


=== romanization

term:[script conversion] from non-Roman to Roman script by means of term:[transliteration], transcription <activity> or both

[.source]
<<ISO5127,clause="3.1.6.14">>


=== transliteration system

a set of rules for term:[transliteration] of a source
 term:[script] to a target script


=== romanization system

a set of rules for term:[romanization] of a source term:[script]
to a target script

//system for representing a word <orthographic word> in a writing system
//through romanization


=== script conversion system

a set of rules for term:[script-conversion]


////
=== writing system

system for writing a language, including the script and character set used

[.source]
<<ISO5127,clause="3.1.6.01">>
////

=== code

_data_ (<<ISO5127,clause=3.1.13.10>>) transformed or represented in different forms
according to a pre-established _set_ (<<ISO5127,3.1.1.09>>) of rules

////
{{ISO5127,clause=3.1.13.10,data}} transformed or represented in different forms
according to a pre-established {{ISO5127,3.1.1.09,set}} of rules
////

[.source]
<<ISO5127,clause="3.1.13.10">>, Note 1 to entry is omitted.


=== language code

combination of characters used to represent the name of a term:[language] or languages

[.source]
<<ISO5127,clause="3.2.5.14">>


=== script code

combination of characters used to represent the name of a term:[script]

[.source]
<<ISO15924,clause="3.8">>


=== script conversion system code

term:[code] used to represent a term:[script conversion system]


////

=== transliterated text

text output of a transliteration system on a transliteration source

=== transliteration script

script form produced by a transliteration system on the transliteration source


=== source language

language used in the transliteration source

=== source script

script used in the transliteration source

////
