
[[terms]]
[source=ISO5127]
== Terms and definitions


=== script

particular graphic representation or class of representations of a set of
characters used to write one or more languages

[.source]
<<ISO5127,clause="3.1.6.02">>



=== spelling system

set of rules governing the orthography of a language

NOTE: Typically, a spelling system defines how the spoken form of a
language is represented in writing.
Several languages have undergone orthographic reforms which means they have had
different spelling systems.


=== natural language

language which is or was in active use in a community of people, and the rules of which are mainly deduced from the usage

[.source]
<<ISO5127,clause=3.1.5.02>>

=== character

member of a set of elements that is used for the representation, organization, or control of data

[.source]
<<ISO5127,clause="3.1.4.02">>

=== written language

{{natural language}} realized through the writing of {{character,characters}}

[.source]
<<ISO5127,clause="3.1.5.04">>


=== written language conversion

process whereby one {{spelling system}} is converted into another spelling system

NOTE: This is a general term that includes script conversion but also,
e.g., cases when a language changes its orthography without changing the script.


=== transliteration

process which consists of representing the characters of an alphabetical or
syllabic system of writing by the characters of a conversion alphabet


=== transcription

process whereby the sounds of a given language are noted by the system of signs
of a conversion language


=== romanization

script conversion from non-Roman to Roman {{script}}
by means of {{transliteration}}, {{transcription}} or both

[.source]
<<ISO5127,clause="3.1.6.14">>


=== written language conversion system

set of rules for {{written language conversion}}


=== language code

combination of characters used to represent the name of a _language_ (<<ISO5127,clause="3.1.5.01">>) or languages

[.source]
<<ISO5127,clause="3.2.5.14">>


=== script code

combination of characters used to represent the name of a {{script}}

[.source]
<<ISO15924,clause="3.8">>


=== conversion system code

combination of characters used in a structured way to represent a
{{written language conversion system}}


////

=== transliterated text

text output of a transliteration system on a transliteration source

=== transliteration script

script form produced by a transliteration system on the transliteration source


=== source language

language used in the transliteration source

=== source script

script used in the transliteration source

////
