
[[terms]]
//[source=ISO5127]
== Terms and definitions


[[term-script]]
=== script

particular graphic representation or class of representations of a set of characters used to write one or more _languages_ (<<term-language>>)

[.source]
<<ISO5127,clause="3.1.6.02">>


[[term-language]]
=== language

systematic use of sounds, characters, symbols or signs to express meaning or communicate meaning or a message

[.source]
<<ISO5127,clause="3.1.5.01">>


[[term-script-conversion]]
=== script conversion

operation to convert a _script_ (<<term-script>>) into another script without change of _language_ (<<term-language>>)


[[term-transliteration]]
=== transliteration

operation which consists of representing the characters of an entirely alphabetical character or alphanumeric character writing system by the characters of the conversion alphabet

[.source]
<<ISO5127,clause="3.1.6.11">>


[[term-romanization]]
=== romanization

_script conversion_ (<<term-script-conversion>>) from non-Roman to Roman script by means of _transliteration_ (<<term-transliteration>>), transcription <activity> or both

[.source]
<<ISO5127,clause="3.1.6.14">>


[[term-transliteration-system]]
=== transliteration system

system for _transliteration_ (<<term-transliteration>>) of a source _script_ (<<term-script>>) to a target script


[[term-romanization-system]]
=== romanization system

system for _romanization_ (<<term-romanization>>) of a source _script_ (<<term-script>>) to a target script

//system for representing a word <orthographic word> in a writing system
//through romanization


[[term-script-conversion-system]]
=== script conversion system

system for _script conversion_ (<<term-script-conversion>>)


////
=== writing system

system for writing a language, including the script and character set used

[.source]
<<ISO5127,clause="3.1.6.01">>
////

[[term-code]]
=== code

_data_ (<<ISO5127,clause=3.1.13.10>>) transformed or represented in different forms
according to a pre-established _set_ (<<ISO5127,3.1.1.09>>) of rules

////
{{ISO5127,clause=3.1.13.10,data}} transformed or represented in different forms
according to a pre-established {{ISO5127,3.1.1.09,set}} of rules
////

[.source]
<<ISO5127,clause="3.1.13.10">>, Note 1 to entry is omitted.


=== language code

combination of characters used to represent the name of a _language_ (<<term-language>>) or languages

[.source]
<<ISO5127,clause="3.2.5.14">>


=== script code

combination of characters used to represent the name of a _script_ (<<term-script>>)

[.source]
<<ISO15924,clause="3.8">>


=== script conversion system code

_code_ (<<term-code>>) used to represent a _script conversion system_ (<<term-script-conversion-system>>)


////

=== transliterated text

text output of a transliteration system on a transliteration source

=== transliteration script

script form produced by a transliteration system on the transliteration source


=== source language

language used in the transliteration source

=== source script

script used in the transliteration source

////

