
[[conversion-system-codes]]
== Conversion system codes

[[structure-of-conversion-system-codes]]
=== Structure of conversion system codes

==== General

A conversion system code must consist of four segments:

- titular segment
- source spelling system segment
- target spelling system segment
- identifying segment

Each segment must consist of one or more elements.


[[construction-of-the-conversion-system-code]]
==== Construction of the conversion system code

The following rules are to be adhered to for the construction of a conversion
system code:

* The codes shall consist of elements from the following Unicode ranges:
  ** DIGIT ZERO through DIGIT NINE (U+0030 -- U+0039)
  ** LATIN CAPITAL LETTER A through LATIN CAPITAL LETTER Z (U+0041 -- U+005A)
  ** LATIN SMALL LETTER A through LATIN SMALL LETTER Z (U+0061 -- U+007A)

* Segments shall be separated by a single "COLON" ("`:`", Unicode U+003A).

* Elements within a segment shall be separated by
  a single "HYPHEN-MINUS" ("`-`", Unicode U+002D).

* "HYPHEN-MINUS" ("`-`", Unicode U+002D)
  within an element (e.g. `233-3`) will also be accepted.

* Other characters in the elements not covered by the above should be omitted or
substituted.


[[titular-segment]]
==== Titular segment

This part will contain a reference to the conversion system authority or
authorities by using identifiers, the list of which is maintained by ISO
{docnumber}/RA.
If an authority cannot be identified but the conversion system has a national
character and/or is used by the government, the 2-letter country code from
<<ISO3166-1>> may be used as the conversion system authority.
If no conversion system authorities can be identified or its identification
is not relevant, "Var" (varia) is used as the titular segment.
See <<conversion-system-authority>> for more details.


[[source-spelling-system-segment]]
==== Source spelling system segment

Except as specified in <<abbreviated-conversion-system-codes>>
a script code would be a mandatory element.
Language-specific spelling systems have also language codes.
In order to cover more specific needs the following four elements
in the order given may be used:

- language code
  (3-letter code from <<ISO639-2>> or <<ISO639-3>> with preference to terminological codes.
  If a synonym is used from ISO 639-2, the ISO 639-2/T associated code should be used.
  ISO 639-2/T codes are intended to be used for terminology applications.)
- script code (4-letter code from <<ISO15924>>)
- country code (2-letter code from <<ISO3166-1>>)
- spelling system extension (an ad hoc string to refer to a non-default spelling
system of a language, such as old orthography)


[example]
`ind-Latn-pre1972` (Indonesian language using the pre-1972 orthography)

[example]
`bos-Arab` (Bosnian language using Arabic script)

[example]
`uzb-Arab-AF` (Uzbek language as used in Afghanistan)


[[target-spelling-system-segment]]
==== Target spelling system segment

This part may have the same four elements as listed in <<source-spelling-system-segment>>.


[[identifying-segment]]
==== Identifying segment

This part will serve to distinguish by version, year of issue, etc. conversion
systems that otherwise have the same scope. It may also contain elements
necessary for the recognition of the system itself if the system has some kind
of identification element. All in all, the following elements may occur (in the
order given):

- identifying numbers, letters or else (such as standard number, e.g. 843)
- version number (e.g. `v6`, `v4-1`)
- year of adoption
- year of issue
- method identifier (if a standard devises more than one method of conversion,
  this optional ad hoc identifier could be used for distinction)

Should there be cases when no elements can be used for this part, "na" (not
applicable) will be the substitute.

[example]
`2017` is the identifying segment of the system coded as `UN:ara-Arab:Latn:2017`.


[[requirements-for-new-conversion-system-codes]]
=== Requirements for new conversion system codes

Additions to the list of conversion system codes shall be made on the basis of information from upon the request of a member of ISO {docnumber}/AG or the conversion system authority that manages this system.

The ISO {docnumber}/AG will decide upon the addition, on the basis of the justification given for the actual requirements for international interchange. Code elements will be allocated accordingly.

A written language conversion system is eligible for a conversion system code assignment if it fulfills one of the following criteria:

* The system has been approved for official use at some level of government.

* The system has been developed and used by educational/scientific institutions, published in a peer reviewed scientific publication.

* The system has been in substantial usage.


Assigning of a conversion system code also requires demonstration of one of the following usage factors:

* Necessity of identification of the system in interchange.
* Necessity of identification of the system in data encoding.

NOTE: Systems that are used in isolation or only for temporary usage do not need to have assigned codes.

////
Additions to the official and international time scale authorities require additional criteria:

* An official time scale authority must be endorsed by a body receiving direct authority by a member of the United Nations.
* An international time scale authority must be endorsed by an international standardization body in liaison with the ISO {docnumber}/AG.
////


[[scs-deprecation]]
=== Deprecation of conversion system codes

Deprecation of conversion system codes shall be made upon
request of a member of ISO {docnumber}/AG
or the conversion system authority that manages the system.

The ISO {docnumber}/AG will decide upon the marking of deprecation, on the basis
of the information received. The corresponding code is reserved
for backwards-compatibility.

NOTE: Deprecation only applies to the code representation of the written languages
conversion system, and not the system itself.
For example, deprecation may be necessary when the authority undergoes a rename.


[[user-assigned-system-codes]]
=== User assigned conversion system codes

If users need codes to represent conversion systems
not included in the conversion system registry, the code prefix of `zz`
can be used, which must be placed at the beginning of the conversion system code,
in the titular segment, and followed by a "HYPHEN MINUS" character ("`-`",
Unicode U+002D).

NOTE: Users are advised that the above series of codes are not universally used,
those code elements are not compatible between different entities.


[[capitalization-of-conversion-system-codes]]
=== Capitalization of conversion system codes

Conversion system codes will use capitalization according to the relevant
standards but this does not have any distinctive meaning.
E.g., an all lower case code would be an equally valid code.


[[abbreviated-conversion-system-codes]]
=== Abbreviated conversion system codes

In case of user demand, abbreviated conversion system codes may additionally be
registered whereby in identifying language-specific spelling systems script
codes are omitted if they can be considered as default scripts for the languages
concerned.
Examples are given in <<examples-of-conversion-system-codes>>.
Authoritative sources, such as Common Locale Data Repository (CLDR)
of the Unicode Consortium,
should  be consulted when determining default scripts for languages.

[[examples-of-conversion-system-codes]]
=== Examples of conversion system codes

The examples given here are only indicative and do not guarantee that such codes
will be actually registered.

[example]
`UN:ara-Arab:Latn:2017` (possible abbreviation -- `UN:ara:Latn:2017`; United Nations system for the romanization of Arabic,
    approved 2017)

[example]
`UN:mon-Mong-CN:Latn:1977` (possible abbreviation -- `UN:mon-CN:Latn:1977`; United Nations system for the romanization of Mongolian
    in China, approved 1977)

[example]
`ALA-LC:mal-Mlym:Latn:2012` (possible abbreviation -- `ALA-LC:mal:Latn:2012`; ALA-LC romanization system that
transliterates the Malayam language from Malayam script characters into Latin
script)

[example]
`ISO:Cyrl:Latn:9-1995` (<<ISO9>> for the transliteration into Latin of
    Cyrillic characters)

[example]
`ICAO:Arab:Latn:2015` (ICAO rules for rendering Arabic-script names in Latin
    letters, issued in 2015)

[example]
`DIN:bel-Cyrl:Latn:1460-1982` (possible abbreviation -- `DIN:bel:Latn:1460-1982`; <<DIN1460>> for the transliteration of Belarusian
    into Latin)

[[example-udm-est]]
[example]
`ESKT:udm-Cyrl:est-Latn:2021` (possible abbreviation -- `ESKT:udm:est:2021`; Estonian Language Committee’s rules for rendering Udmurt
    names in Estonian texts, approved 2021)

[example]
`LV:eng-Latn:lav-Latn:2006` (possible abbreviation -- `LV:eng:lav:2006`; official instructions in Latvia on rendering English proper names in Latvian, issued in 2006)

NOTE: Target spelling systems may also be language-specific.
E.g., <<example-udm-est>> denotes a system to represent Udmurt names
in Estonian texts using the Estonian alphabet,
not Latin as a whole.


// === Written language conversion systems
//
// ==== General
//
// Written language conversion systems are used to convert writing systems
// into other scripts, and in the case of romanization systems, into Roman script.
//
//
// ==== Code and identifier
//
// ===== Principles for inclusion in the list of transliteration and romanization systems
//
// ====== List
//
// The list of written language conversion systems in this document includes known
// transliteration and romanization systems from official sources.
//
//
// ====== Source of names
//
// Names and description of written language conversion systems are obtained from
// authoritative sources.
//
//
// ====== Current status of names
//
// Written language conversion systems listed in this document are intended to reflect the
// current situation, at the time of issue of the latest update of this document.
//
//
//
// ===== Principles for allocation of code elements
//
// ====== Relationship with names
//
// The code for a written language conversion system has the structure of a list, with all
// elements joined by a "FIGURE DASH" character ("`-`", Unicode U+2012).
//
// The elements must conform to the following order:
//
// * `authority-identifier` designates the authority that manages the
// transliteration system;
// * `lang-code` designates the ISO-639 language code the transliteration system processes;
// * `source-script-code` designates the script code of the text taken as input by the transliteration system;
// * `target-script-code` designates the script code of the text produced by the transliteration system;
// * `system-identifier` designates a unique identifier for the transliteration system, such as edition year, document identifier, and system name.
//
// [example]
// `alalc-mal-mlym-latn-2012` for the ALA-LC Romanization system that
// transliterates the Malayam language from Malayam script characters into Latin
// script. The system identifier here is considered to be `2012`.
//
// [example]
// `iso-ukr-Cyrl-Latn-9-1995` for the transliteration system that transliterates
// the Ukrainian language from Cyrillic script into Latin script according to
// <<ISO9>>. The system identifier here is considered to be `9-1995`.
//
//
// ====== Construction of the authority identifiers
//
// The following rules are to be adhered to for the assignment of the authority
// codes:
//
// * The authority identifier uses combinations, in lower case, of the
// 26-character Latin
// alphabet.
//
// * Codes shall encourage descriptive and distinguishable alphabetic names.
//
// * Two-character authority identifiers are reserved for <<ISO3166-1>> codes,
// which
// designate that the authority is the government that is represented by the
// particular <<ISO3166-1>> code.
//
//
// ====== Construction of the language code
//
// The language code must be a code listed in any part of <<ISO639>>.
//
// [example]
// `iso-ara-arab-latn-233-2-1993` applies to the Arabic language written in Arabic script.
//
//
// When a written language conversion system applies to more than one language,
// the conversion system authority that manages that system
// should determine which of the following approaches should be taken:
//
// . consider this system as multiple systems, with each individual systems
// applying to a single language code; or
// . consider this system as a single system, where the <<ISO639-3>> code of `mul`
// applies.
//
// [example]
// `icao-mul-arab-latn-2015` applies to multiple languages written in Arabic
// script, and is encoded as a single system.
//
// [example]
// `din-bel-cyrl-latn-1460-1982` and `din-bul-cyrl-latn-1460-1982` are both defined
// in <<DIN1460>>, but they are encoded as separate systems for separate languages.
//
//
// ====== Construction of the script codes
//
// The script code must be a code listed in <<ISO15924>>.
//
//
//
//
// ===== List of conversion system codes and their data elements
//
// The list of conversion system codes is initially defined in <<annex-system-codes>>.
// Additional and new entries will be provided by the ISO {docnumber}/RA.
//
// Data attributes provided in the list is defined in <<sc-data-model>>.
