
[[conversion-system-codes]]
== Conversion system codes


[[structure-of-conversion-system-codes]]
=== Structure of conversion system codes

A conversion system code will consist of four segments, or parts separated by a
colon (:): titular segment, source spelling system segment, target spelling
system segment and identifying segment. Each segment may consist of more than
one element separated by a hyphen (-). A valid code must have at least one
element in each segment.

[[titular-segment]]
==== Titular segment

This part will contain a reference to the conversion system authority or
authorities using abbreviations, the list of which is maintained by ISO
{docnumber}/RA.
If an authority cannot be identified but the conversion system has a national
character and/or is used by the government, the 2-letter country code from ISO
3166-1 may be used as the conversion system authority. If no conversion system
authorities cannot be identified or its identification is not relevant, "Var"
(varia) is used as the titular segment. See xx for more details.

[[source-spelling-system-segment]]
==== Source spelling system segment

To identify a spelling system usually a language code or a script code or both
would be sufficient but to cover more specific needs the following four elements
in the order given may be used:

- language code (3-letter code from ISO 639-2 or 639-3 with preference to
terminological codes)
- spelling system extension (an ad hoc string to refer to a non-default spelling
system of a language, such as old orthography)
- script code (4-letter code from ISO 15924)
- country code (2-letter code from ISO 3166-1)

Examples: ind-pre1972 (Indonesian language using the pre-1972 orthography),
bos-Arab (Bosnian language using Arabic script), uzb-AF (Uzbek language as used
in Afghanistan).

[[target-spelling-system-segment]]
==== Target spelling system segment

This part may have the same four elements as listed in <<source-spelling-system-segment>>.

[[identifying-segment]]
==== Identifying segment

This part will serve to distinguish by version, year of issue, etc. conversion
systems that otherwise have the same scope. It may also contain elements
necessary for the recognition of the system itself if the system has some kind
of identification element. All in all, the following elements may occur (in the
order given):

- identifying numbers, letters or else (such as standard number, e.g. 843)
- version number (e.g. v6, v4-1)
- year of adoption
- year of issue
- method number (if a standard devises more than one method of conversion, this
optional ad hoc number could be used for distinction)

Should there be cases when no elements can be used for this part, "na" (not
applicable) will be the substitute.

[[capitalization-of-conversion-system-codes]]
=== Capitalization of conversion system codes

Conversion system codes will use capitalization according to the relevant
standards but this does not have any distinctive meaning.
E.g., an all lower case code would be an equally valid code.

[[permitted-characters-in-conversion-system-codes]]
=== Permitted characters in conversion system codes

The codes will use alphabetic letters and numbers only, in addition colons serve
to separate segments and hyphens to separate elements.
Hyphens within elements (e.g. 233-3) will also be accepted but other
non-alphabetic characters should be omitted or substituted.

[[conversion-system-codes-and-alias-codes]]
=== Conversion system codes and alias codes

In order to keep the conversion system code short, it is recommended to identify
a spelling system as shortly as possible omitting the default elements.
E.g., Icelandic language (code: isl) uses by default Latin script (code: Latn)
and is spoken in Iceland (code: IS), therefore the notation isl will be equal to
isl-Latn-IS.
But there will be cases when certain languages are in transition and the default
elements are difficult to determine, or cases when the default elements have
changed after the registration of the conversion system code.
In this case an alias conversion system code may be established with more
elements included but the old code is preserved.

Examples of conversion system codes:

- UN:araLatn:2017 (United Nations system for the romanization of Arabic,
  approved 2017)
- UN:mon-CN:Latn:1977 (United Nations system for the romanization of Mongolian
  in China, approved 1977)
- ISO:Cyrl:Latn:9-1995 (ISO 9:1995 for the transliteration into Latin of
  Cyrillic characters)
- ICAO:Arab:Latn:2015 (ICAO rules for rendering Arabic-script names in Latin
  letters, issued in 2015)
- DIN:bel:Latn:1460-1982 (DIN 1460:1982 for the transliteration of Belarusian
  into Latin)
- ESKT:udm:est:2021 (Estonian Language Committee’s rules for rendering Udmurt
  names in Estonian texts, approved 2021)

NOTE: In some cases the target spelling system may also be indicated by a
language code rather than script code.

E.g. ESKT:udm:est:2021 denotes a system to represent Udmurt names in Estonian
texts using the Estonian alphabet, not Latin as a whole.
