
[[conversion-system-authority]]
== Conversion system authority

=== General

A conversion system authority is a competent authority that creates,
publishes and/or manages written language conversion systems.

Authorities that are no longer competent will depend on ISO {docnumber}/AG for
managing codes, which will be considered on a case-by-case basis.


[[scsa-requirements]]
=== Requirements

==== General

A conversion system authority should:

. have at least one written language conversion system eligible for a conversion
system code;
. [[scsa-requirements-b]]be competent in managing its written language conversion systems
(<<scsa-competency>>).


==== Inactive authorities

If a conversion system authority does not meet requirements outlined in
<<scsa-requirements-b>>,
it is considered "`inactive`".


==== Varia authorities

The "`Varia systems`" (Var) conversion system authority is managed by
ISO {docnumber}/AG to represent written language conversion systems that:

. have a need to be represented as determined by ISO {docnumber}/AG;
. yet do not have a clear extant authority.


[[scsa-competency]]
==== Competency

A competent conversion system authority is a recognized institution that has standardized
processes surrounding the management of the written language conversion systems,
covering the following processes:

. planning of written language conversion systems, including the process of designing and
defining written language conversion systems; and
. performing changes to written language conversion systems are well planned.

It is recommended for a competent conversion system authority to also establish
standardized processes for the following:

. public announcement and dissemination of its written language conversion systems; and
. allows a public review period for people affected by written language conversion systems
under its management prior to enactment.


=== Registration

The ISO {docnumber}/AG is tasked with managing a list of
conversion system authorities.


=== Conversion system authority identifiers

==== Principles for construction of identifiers

===== Relationship with names

The principle behind the alphabetic identifiers for conversion system
authorities is a visual association between the conversion system
authorities' names and their corresponding identifiers.

In applying this principle, the identifiers will be generally assigned on
the basis of the abbreviated names of the conversion system authorities,
thus avoiding, wherever possible, any reflection of their political status.


[[construction-of-the-alphabetic-identifier]]
===== Construction of the alphabetic identifier

The following rules shall be adhered to for the construction of the alphabetic
identifier:

* The maximum length of the identifier shall be 16 characters.

* The identifier shall consist of elements from the following Unicode ranges:
  ** DIGIT ZERO through DIGIT NINE (U+0030 -- U+0039)
  ** LATIN CAPITAL LETTER A through LATIN CAPITAL LETTER Z (U+0041 -- U+005A)
  ** LATIN SMALL LETTER A through LATIN SMALL LETTER Z (U+0061 -- U+007A)

* The identifier elements shall be separated by a single HYPHEN-MINUS (U+002D).

// * Other non-alphabetic characters should be omitted or substituted.

* The minimal length of the identifier is 3 characters to encourage the creation
of descriptive and distinguishable elements, with the exception of the following:
  ** UN, for United Nations

* Identifiers with 2 characters shall be reserved for codes in <<ISO3166-1>>,
each representing the administration authority of the particular jurisdiction.


===== Capitalization of conversion system authority identifiers

Conversion system authority identifiers will use capitalization like in ordinary
abbreviations, but this does not have any distinctive meaning.
For example, an all lower case identifier will be an equally valid identifier.


==== Examples of conversion system authority identifiers

The examples given here are only indicative.

[example]
`ISO` for International Organization for Standardization

[example]
`BGN-PCGN` for the United States Board on Geographic Names - Permanent Committee
on Geographical Names for British Official Use

[example]
`ALA-LC` for American Library Association - Library of Congress

[example]
`DIN` for German Institute for Standardization

[example]
`ICAO` for International Civil Aviation Organization

[example]
`UN` for United Nations
