
[[conversion-system-authority]]
== Conversion system authority

=== General

A conversion system authority is a competent authority that creates,
publishes and/or manages definitions of written languages conversion systems.

Authorities that are no longer competent will depend on ISO {docnumber}/AG for
managing codes, which will be considered on a case-by-case basis.


[[scsa-requirements]]
=== Requirements

==== General

A conversion system authority should:

. have at least one written languages conversion system eligible for a conversion
system code;
. [[scsa-requirements-b]]be competent in managing its written languages conversion systems
(<<scsa-competency>>).


==== Inactive authorities

If a conversion system authority does not meet requirements outlined in
<<scsa-requirements-b>>,
it is considered "`inactive`".


==== Reserved authorities

The "`Various systems`" conversion system authority is managed by
ISO {docnumber}/AG to represent written languages conversion systems that:

. have a need to be represented as determined by ISO {docnumber}/AG;
. yet do not have a clear extant authority.



[[scsa-competency]]
==== Competency

A competent conversion system authority is one that has standardized
processes surrounding the management of the written languages conversion systems,
covering at least the following processes:

. planning of written languages conversion systems, including the process of designing and
defining written languages conversion systems;
. performing changes to written languages conversion systems are well planned;
. public announcement and dissemination of its written languages conversion systems; and
. allows a public review period for people affected by written languages conversion systems
under its management prior to enactment.


=== Registration

The ISO {docnumber}/AG is tasked with managing a list of
conversion system authorities.



=== Code and identifier


==== Principles for inclusion in the list of conversion system authority

===== List

The list of conversion system authorities in this document includes
known authorities, such as ISO.


===== Source of names

Names and abbreviations of written languages conversion systems are obtained from the
conversion system authorities.


===== Current status of names

Conversion system authorities listed in this document are intended to
reflect the current situation, at the time of issue of the latest update of this
document.



==== Principles for allocation of code elements

===== Relationship with names

The principle behind the alphabetic codes for conversion system
authorities is a visual association between the conversion system
authorities and their corresponding code elements.

In applying this principle, the code elements have generally been assigned on
the basis of the abbreviated names of the conversion system authorities,
thus avoiding, wherever possible, any reflection of their political status.

[example]
`iso` for ISO.

[example]
`bgnpcgn` for the United States Board on Geographic Names - Permanent Committee
on Geographical Names for British Official Use.


===== Construction of the alphabetic code

The following rules are to be adhered to for the assignment of the alphabetic
code:

* The alphabetic code uses combinations, in lower case, of a maximum of 16
letters of the 26-character Latin alphabet.

* The minimal length of the code is 3 letters to encourage descriptive and
distinguishable alphabetic names.

* Codes with 2 letters are reserved for codes in <<ISO3166-1>>, each
representing the administration authority of the particular jurisdiction.

* The specific code prefix of `xx` is reserved and is used as the prefix of
user-assignable conversion system authority codes.


===== User assigned code elements

If users need code elements to represent conversion system authorities
not included in the conversion system authority registry, the code prefix
of `xx` can be used, being a reserved code point `xx` for private user
assignment.

The code length for the conversion system authority identifier must be 3
or more letters.

[example]
`xxunece` is an example of a user-assigned private code for a conversion
system authority published by the UN/ECE.

NOTE: Users are advised that the above series of codes are not universally used,
those code elements are not compatible between different entities.



==== List of conversion system authority codes and their data elements

The list of conversion system authority codes is initially defined in
<<annex-conversion-system-authorities>>.
Additional and new entries will be provided by the ISO {docnumber}/RA.

Data attributes provided in the list are defined in <<sc-authority-data-model>>.
