
[[conversion-system-authority]]
== Conversion system authority

=== General

A conversion system authority is a competent authority that creates,
publishes and/or manages written languages conversion systems.

Authorities that are no longer competent will depend on ISO {docnumber}/AG for
managing codes, which will be considered on a case-by-case basis.


[[scsa-requirements]]
=== Requirements

==== General

A conversion system authority should:

. have at least one written languages conversion system eligible for a conversion
system code;
. [[scsa-requirements-b]]be competent in managing its written languages conversion systems
(<<scsa-competency>>).


==== Inactive authorities

If a conversion system authority does not meet requirements outlined in
<<scsa-requirements-b>>,
it is considered "`inactive`".


==== Varia authorities

The "`Various systems`" (Var) conversion system authority is managed by
ISO {docnumber}/AG to represent written languages conversion systems that:

. have a need to be represented as determined by ISO {docnumber}/AG;
. yet do not have a clear extant authority.


[[scsa-competency]]
==== Competency

A competent conversion system authority is one that has standardized
processes surrounding the management of the written languages conversion systems,
covering at least the following processes:

. planning of written languages conversion systems, including the process of designing and
defining written languages conversion systems;
. performing changes to written languages conversion systems are well planned;
. public announcement and dissemination of its written languages conversion systems; and
. allows a public review period for people affected by written languages conversion systems
under its management prior to enactment.


=== Registration

The ISO {docnumber}/AG is tasked with managing a list of
conversion system authorities.


=== Conversion system authority identifiers

==== Principles for construction of identifiers

===== Relationship with names

The principle behind the alphabetic identifiers for conversion system
authorities is a visual association between the conversion system
authorities' names and their corresponding identifiers.

In applying this principle, the identifiers will be generally assigned on
the basis of the abbreviated names of the conversion system authorities,
thus avoiding, wherever possible, any reflection of their political status.


[[construction-of-the-alphabetic-identifier]]
===== Construction of the alphabetic identifier

The following rules are to be adhered to for the assignment of the alphabetic
identifier:

* The alphabetic identifier uses combinations of a maximum of 16 characters from
the following Unicode ranges:
  ** digits (U+0030 -- U+0039)
  ** hyphen-minus (U+002D)
  ** Latin uppercase letters (U+0041 -- U+005A)
  ** Latin lowercase letters (U+0061 -- U+007A)

* The minimal length of the identifier is 3 letters to encourage the creation of
descriptive and distinguishable elements.

* Identifiers with 2 letters are reserved for codes in <<ISO3166-1>>, each
representing the administration authority of the particular jurisdiction.


===== Capitalization of conversion system authority identifiers

Conversion system authority identifiers will use capitalization like in ordinary
abbreviations, but this does not have any distinctive meaning.
E.g., an all lower case identifier would be an equally valid identifier.


==== Examples of conversion system authority identifiers

The examples given here are only indicative and do not guarantee that such
identifiers will be actually registered.

[example]
`ISO` for International Organization of Standardization

[example]
`BGN-PCGN` for the United States Board on Geographic Names - Permanent Committee
on Geographical Names for British Official Use

[example]
`ALA-LC` for American Library Association - Library of Congress

[example]
`DIN` for German Institute for Standardization

[example]
`ICAO` for International Civil Aviation Organization

[example]
`UN` for United Nations
