
== Script conversion systems

=== General

Script conversion systems are used to convert writing systems
into other scripts, and in the case of romanization systems, into Roman script.


[[sc-data-model]]
=== Data model and attributes

==== General

[plantuml]
....
include::../models/style.uml.inc[]
include::../models/system.wsd[]
....


==== Code

A code that identifies the script conversion system.


==== Name

A name that represents the script conversion system.


==== Source script code

The script code of the script used in the source text. This code is from <<ISO15924>>.


==== Target script code

The script code of the script used in the output text. This code is from <<ISO15924>>.


==== Language code

The language code that identifies the source language being processed
by the script conversion system.

The language code should be qualified to a source of language codes.
For example, <<ISO639-1>>, <<ISO639-2>>, <<ISO639-3>>, <<ISO639-5>>
contain language codes that can be selected from.

If a synonym is used from <<ISO639-2>>, the ISO 639-2/T associated code should be used. ISO 639-2/T codes are intended to be used for terminology applications.


==== System identifier

A system may be uniquely identified by an identifier, an edition, a version or a sequence of characters.

This element is mandatory if the authority manages or plans to manage multiple script conversion systems.

It may or may not be derived from the adoption date.

[example]
`2013` is the system identifier of the system coded as `un-lao-laoo-latn-2013`.


==== Adoption date

The date of the adoption of the script conversation system by the authority.


==== Remarks

Any further notes.


=== Code and identifier

==== Principles for inclusion in the list of transliteration and romanization systems

===== List

The list of transliteration and romanization systems in this document includes known
transliteration and romanization systems from official sources.


===== Source of names

Names and description of transliteration and romanization systems are
obtained from authoritative sources.


===== Current status of names

Script conversion systems listed in this document are intended to reflect the current situation, at the time of issue of the latest update of this document.



==== Principles for allocation of code elements

===== Relationship with names

Script conversion systems have codes in the following format:

[source]
----
[authority-code]"-"[lang-code]"-"[source-script-code]"-"[target-script-code]"-"[system-identifier]
----

Where,
* `authority-code` designates the authority that manages the transliteration system;
* `lang-code` designates the ISO-639 language code the transliteration system processes;
* `source-script-code` designates the script code of the text taken as input by the transliteration system;
* `target-script-code` designates the script code of the text produced by the transliteration system;
* `system-identifier` designates a unique identifier for the transliteration system, such as edition year, document identifier, and system name.

[example]
`alalc-mal-mlym-latn-2012` for the ALA-LC Romanization system that transliterates the Malayam language from Malayam script characters into Latin script. The system identifier here is considered to be `2012`.

[example]
`iso-ukr-Cyrl-Latn-9-1995` for the transliteration system that transliterates the Ukrainian language from Cyrillic script into Latin script according to <<ISO9>>. The system identifier here is considered to be `9-1995`.


===== Construction of the authority codes

The following rules are to be adhered to for the assignment of the authority codes:

* The authority code uses combinations, in lower case, of the 26-character Latin alphabet.

* Codes shall encourage descriptive and distinguishable alphabetic names.

* Two-character authority codes are reserved for <<ISO3166-1>> codes, which designate that the authority
is the government that is represented by the particular <<ISO3166-1>> code.


===== Construction of the language code

The language code must be a code listed in any part of <<ISO639>>.


===== Construction of the script codes

The language code must be a code listed in <<ISO15924>>.


===== User assigned system codes

If users need system codes to represent transliteration and romanization systems not included in the script conversion system registry, the code prefix of `zz` can be used.

Such transliteration and romanization system identifiers are in the following format:

[source]
----
"zz"[authority-code]"-"[lang-code]"-"[source-script-code]"-"[target-script-code]"-"[system-identifier]
----

NOTE: Users are advised that the above series of codes are not universally used, those code elements are not compatible between different entities.


==== List of transliteration and romanization system and their code elements

The list of items composing the content of the country code is initially defined in <<annex-system-codes>>.
Additional and new entries will be listed by the ISO {docnumber}/AG.

Data attributes provided in the list is defined in <<sc-data-model>>.

