
[[common-data]]
== Data model and attributes

=== Common data model and attributes

==== General

The data models in this clause are used by other data models specified in
this document.

==== Data models

lutaml_diagram::models/datatypes.lutaml[]


[[iso-639]]
==== Usage of ISO 639 code elements

`iso639Code` represents code elements from <<ISO639-2>>,
<<ISO639-3>> and <<ISO639-5>> for reference to languages.


[[iso-15924]]
==== Usage of ISO 15924 code elements

`iso15924Code` represents code elements from <<ISO15924>> for reference to
scripts.


[[iso-3166]]
==== Usage of ISO 3166 code elements

`iso3166Code` represents country codes from <<ISO3166-1>>.


[[iso-8601]]
==== Usage of ISO 8601 expressions

`iso8601Expression` represents datetime expressions that are compliant with
<<ISO8601>>.


[[sc-authority-data-model]]
=== System authority data model and attributes

==== Diagram

lutaml_diagram::models/authority.lutaml[]


==== Conversion System Authority

authorityIdentifier:: An identifier that represents the conversion system authority (<<titular-segment>>).

name:: The identifiable short name that uniquely identifies the conversion
system authority.

remarks:: Any further notes.


==== Authority Identifier

Either a 2-letter `iso3166Code`,
or a `String` under the constraints of <<construction-of-the-alphabetic-identifier>>.


[[sc-data-model]]
=== Conversion system data model and attributes

==== Diagram

lutaml_diagram::models/system.lutaml[]


==== Written Language Conversion System

code:: A code that identifies the written language conversion system.

name:: A name that represents the written language conversion system.

authority:: The conversion system authority under which this conversion system belongs.

sourceSpelling:: The spelling system used in the source text.

targetSpelling:: The spelling system used in the output text.

identifyingSegment:: An identifier that distinguishes the written languages
conversion system from others with the same conversion system authority and
spelling scopes.


relations:: Written language conversion systems can be related to other written
language conversion systems in a number of ways.
For example, a written language conversion system may represent an adoption or
variant of another written language conversion system.
+
Hierarchical structures of written language conversion systems can be constructed by means
of relationships.
+
This element is optional.


codeStatus:: An optional code that identifies the current status of the conversion system
code itself.

systemStatus:: An optional code that identifies the current status of the written
language conversion system itself.

remarks:: Any further notes.
+
The date of the adoption of the written language conversion system by the authority may
be noted in the remarks.
+
A typical use case is to show its original code from the original system from
where this code has been imported.
+
[example]
`NOTE: OGC 11-122r1 code urd_Arab2Latn_ODNI_2004`


==== Spelling System

`scriptCode` must be present.
In the case of a language-specific spelling system, `languageCode` is also required.

languageCode:: A 3-letter code from <<ISO639-2>>,
<<ISO639-3>> and <<ISO639-5>> that identifies the source language being
processed.

scriptCode:: A 4-letter code from <<ISO15924>> that identifies the script of the
spelling system.

countryCode:: An optional 2-letter code from <<ISO3166-1>> that identifies the
country associated with the spelling system.

extension:: An optional ad hoc string to refer to a non-default spelling system of a
language.


==== Conversion System Relation

targetSystem:: The conversion system of which this relation is a target.

type:: One or more types of relation that the conversion system has with the
target conversion system.


==== Conversion System Code Status

Examples of system code statuses:

`preferred`:: The current system code is marked as "preferred".

`deprecated`:: The current system code is marked as "deprecated".
+
NOTE: The deprecation marker in no way indicates deprecation of the system
itself.
+
[example]
When a conversion system code has been renamed, maybe due to the renaming of the
corresponding system authority, then the old code can be considered "deprecated"
in favor of the renamed code.
The conversion system itself remains unchanged.


==== Conversion System Status

Examples of system statuses:

`former`:: The current system is marked as "former".

`current`:: The current system is marked as "current".

`inactive`:: The current system is marked as "inactive".
+
[example]
When it has been deprecated of its own accord, it can be considered "inactive".


==== Conversion System Relation Type

Examples of relation types:

`basedOn`:: The current system is based on the target system.
The conversion process inherits certain attributes from the target system.
+
[example]
`ALA-LC:jpn-Hrkt:Latn:1997` is based on `Var:jpn-Hrkt:Latn:Hepburn-1886`.

`basisFor`:: The target system is based on the current system.
It can be thought of as the inverse of `basedOn`.
+
[example]
`Var:jpn-Hrkt:Latn:Hepburn-1886` is the basis for `ALA-LC:jpn-Hrkt:Latn:1997`,
`BGN:jpn-Hrkt:Latn:1930`,
`BGN-PCGN:jpn-Hrkt:Latn:1976` and `BGN-PCGN:jpn-Hrkt:Latn:2017`

`aliasOf`:: The current system is an alias to the target system.
The conversion processes are identical.

`adoptedFrom`:: The current system is adopted from the target system.
The conversion processes may not be identical.

`supersedes`:: The current system supersedes the target system.

`supersededBy`:: The current system is superseded by the target system.

`relatedTo`:: The current system is related to the target system.
