
== Script conversion systems

=== General

Script conversion systems are used to convert writing systems
into other scripts, and in the case of romanization systems, into Roman script.

=== Requirements

[[registration-adding-entry]]
==== Registration of a new script conversion system

Additions to the list of script conversion system codes shall be made on the basis of information from upon the request of a member of ISO {docnumber}/AG or the script conversion system authority that manages this system.

The ISO {docnumber}/AG will decide upon the addition, on the basis of the justification given for the actual requirements for international interchange. Code elements will be allocated accordingly.

A script conversion system is eligible for a script conversion system code assignment if it fulfills one of the following criteria:

* The system has been approved for official use at some level of government;

* The system has been developed and used by educational/scientific institutions, published in a peer reviewed scientific publication;

* The system has been in substantial usage.


Assigning of a script conversion system code also requires demonstration of one of the following usage factors:

* Necessity of identification of the system in interchange;
* Necessity of identification of the system in data encoding.

NOTE: Systems that are used in isolation or only for temporary usage does not need to be assigned codes.

////
Additions to the official and international time scale authorities require additional criteria:

* An official time scale authority must be endorsed by a body receiving direct authority by a member of the United Nations.
* An international time scale authority must be endorsed by an international standardization body in liaison with the ISO {docnumber}/AG.
////


[[scs-deprecation]]
==== Deprecation of a script conversion system

Deprecation of script conversion system codes shall be made upon
request of a member of ISO {docnumber}/AG
or the script conversion system authority that manages the system.

The ISO {docnumber}/AG will decide upon the marking of deprecation, on the basis
of the information received. The corresponding code element is reserved
for backwards-compatibility.

NOTE: Deprecation only applies to the code representation of the script
conversion system, and not the system itself.
For example, when the authority undergoes a rename.


[[sc-data-model]]
=== Data model and attributes

==== General

[plantuml]
....
include::../models/style.uml.inc[]
include::../models/system.wsd[]
include::../models/status.wsd[]
include::../models/relation.wsd[]
....


==== code

A code that identifies the script conversion system.


==== name

A name that represents the script conversion system.


==== language

The language code that identifies the source language being processed
by the script conversion system.

The language code should be qualified to a source of language codes.
For example, <<ISO639-1>>, <<ISO639-2>>, <<ISO639-3>>, <<ISO639-5>>
contain language codes that can be selected from.

If a synonym is used from <<ISO639-2>>, the ISO 639-2/T associated code should
be used. ISO 639-2/T codes are intended to be used for terminology applications.


==== sourceScript

The script code of the script used in the source text. This code is from <<ISO15924>>.


==== targetScript

The script code of the script used in the output text. This code is from <<ISO15924>>.


==== systemIdentifier

A system may be uniquely identified, amongst systems maintained by the same
authority, by an identifier, an edition, a version or a sequence of characters.

This element is mandatory if the authority manages or plans to manage multiple
script conversion systems.

It may be derived from the adoption date if and only if that does not cause
duplicates.
Otherwise the adoption date shall be complemented by the name or number of the
standard / technical specification, or some other data element.

[example]
`2013` is the system identifier of the system coded as `un-lao-laoo-latn-2013`.


==== relations

Script conversion systems can be related to other script conversion systems
in a number of ways. For example, a script conversion system may represent
an adoption or variant of another script conversion system.

Hierarchical structures of script conversion systems can be constructed by means
of relationships.

This element is optional.

`aliasOf`:: the current system is an alias to the target system, the script conversion process is identical
`adoptedFrom`:: the current system is adopted from the target system, the script conversion process may not be identical
`supercedes`:: the current system supercedes the target system
`replacedBy`:: the current system is replaced by the target system
`relatedTo`:: the current system is related to the target system
`basedOn`:: the current system is based on the target system, the script conversion process inherits certain attributes from the target system.


==== status

A system code may be optionally marked as deprecated or preferred.

NOTE: The deprecation marker in no way indicates deprecation of the system
itself.


==== remarks

Any further notes.

The date of the adoption of the script conversation system by the authority may
be noted in the remarks.

A typical use case is to show its original code from the original system from
where this code has been imported.

[example]
`NOTE: OGC 11-122r1 code urd_Arab2Latn_ODNI_2004`


=== Code and identifier

==== Principles for inclusion in the list of transliteration and romanization systems

===== List

The list of script conversion systems in this document includes known
transliteration and romanization systems from official sources.


===== Source of names

Names and description of script conversion systems are obtained from
authoritative sources.


===== Current status of names

Script conversion systems listed in this document are intended to reflect the
current situation, at the time of issue of the latest update of this document.



==== Principles for allocation of code elements

===== Relationship with names

The code for a script conversion system has the structure of a list, with all
elements joined by a "FIGURE DASH" character ("`-`", Unicode U+2012).

The elements must conform to the following order:

* `authority-code` designates the authority that manages the transliteration system;
* `lang-code` designates the ISO-639 language code the transliteration system processes;
* `source-script-code` designates the script code of the text taken as input by the transliteration system;
* `target-script-code` designates the script code of the text produced by the transliteration system;
* `system-identifier` designates a unique identifier for the transliteration system, such as edition year, document identifier, and system name.

[example]
`alalc-mal-mlym-latn-2012` for the ALA-LC Romanization system that
transliterates the Malayam language from Malayam script characters into Latin
script. The system identifier here is considered to be `2012`.

[example]
`iso-ukr-Cyrl-Latn-9-1995` for the transliteration system that transliterates
the Ukrainian language from Cyrillic script into Latin script according to
<<ISO9>>. The system identifier here is considered to be `9-1995`.


===== Construction of the authority codes

The following rules are to be adhered to for the assignment of the authority
codes:

* The authority code uses combinations, in lower case, of the 26-character Latin
alphabet.

* Codes shall encourage descriptive and distinguishable alphabetic names.

* Two-character authority codes are reserved for <<ISO3166-1>> codes, which
designate that the authority is the government that is represented by the
particular <<ISO3166-1>> code.


===== Construction of the language code

The language code must be a code listed in any part of <<ISO639>>.

[example]
`iso-ara-arab-latn-233-2-1993` applies to the Arabic language written in arabic script.


When a script conversion system applies to more than one language,
the script conversion authority that manages that system
should determine which of the following approaches should be taken:

. consider this system as multiple systems, with each individual systems
applying to a single language code; or
. consider this system as a single system, where the <<ISO639-3>> code of `mul`
applies.

[example]
`icao-mul-arab-latn-2015` applies to multiple languages written in Arabic
script, and is encoded as a single system.

[example]
`din-bel-cyrl-latn-1460-1982` and `din-bul-cyrl-latn-1460-1982` are both defined
in <<DIN1460>>, but they are encoded as separate systems for separate languages.


===== Construction of the script codes

The script code must be a code listed in <<ISO15924>>.


===== User assigned system codes

If users need system codes to represent transliteration and romanization systems
not included in the script conversion system registry, the code prefix of `zz`
can be used.

The code for such a system has the structure of a list, with all elements joined
by a "FIGURE DASH" character ("`-`", Unicode U+2012).

The elements must conform to the following order:

* the literal string `zz`
* `authority-code`
* `lang-code`
* `source-script-code`
* `target-script-code`
* `system-identifier`

NOTE: Users are advised that the above series of codes are not universally used,
those code elements are not compatible between different entities.


==== List of script conversion system codes and their data elements

The list of script conversion system codes is initially defined in <<annex-system-codes>>.
Additional and new entries will be provided by the ISO {docnumber}/RA.

Data attributes provided in the list is defined in <<sc-data-model>>.
