
[[AnnexA]]
[appendix,obligation=normative]
== Registration

=== Registration authority (ISO {docnumber}/RA)

==== General

For the purpose of registering conversion system codes and conversion system
authority identifiers, ISO has designated a Registration Authority for ISO
{docnumber}.

ISO maintains a list of Maintenance Agencies and Registration Authorities on the
Internet at the address:

> https://www.iso.org/maintenance_agencies.html

The ISO list identifies the Registration Authority and where the Registration
Authority has published materials related to this standard on the Internet.


==== Functions of the Registration Authority

It has been entrusted with the following functions with regard to
the list of conversion system authorities and written languages conversion
systems, together with code assignments and information associated with each entry:

. to add and eliminate these entries, in accordance with the rules in this document;

. to advise users and ISO member bodies regarding application of such information;

. to update and disseminate such information;

. to maintain a reference list of such information;

. to publish changes made to such information and the history of changes allowing traceability;

. to administer the reservation of the codes.

Changes to the content of the list of entries becomes effective
immediately upon publication.

The criteria provided in <<authority-scsa-codes>> to <<authority-scs-codes>>
shall be observed by the ISO {docnumber}/RA for changes to the list of
conversion system authorities and written languages conversion
systems, their code assignments and associated information,
and for reservations of code elements.


==== Data provided by the Registration Authority

The RA will provide at least the following data on conversion system codes:

- the conversion system code
- the name of the conversion system and its authority
- the source language and script of the conversion system
- the target language and script of the conversion system
- the source bibliographic reference
- method identifier of the conversion system
- status of the conversion system code
- relationship with other conversion systems
- any associated remarks


=== Advisory group (ISO {docnumber}/AG)

==== Principles

For the purpose of increasing transparency and making sure the operations of the
registration authority (ISO {docnumber}/RA) are carried out in accordance with
guidelines provided in this document, the registration authority
will appoint an advisory group of at least 4 members and up to 12 members.

The advisory group will consist of experts knowledgeable in the fields of script
or other type of conversions, information technologies, library management,
the group will also contain a representative of TC 46 and may also contain
representatives of organizations interested in using the conversion system
codes.

==== Consensus phase and voting procedure

As a rule, the advisory group will make its decisions by consensus.
If a vote is needed, the decision is approved when more than half/two-thirds of
members vote for it.


[[authority-scsa-codes]]
=== Operations on the list of conversion system authorities and their identifiers

==== Registration of a new conversion system authority

Additions to the list of conversion system authority identifiers
shall be made on upon request from a member of the ISO {docnumber}/AG.

A conversion system authority is eligible for registration
if it meets the requirements stated in <<scsa-requirements>>.

The proposer is responsible for providing justification to the
ISO {docnumber}/AG regarding the eligibility of such addition.

The ISO {docnumber}/AG will decide upon the addition, on the
basis of eligibility and usage justification.

Identifiers will be allocated by the ISO {docnumber}/AG at its
discretion.


==== Marking a conversion system authority inactive

A conversion system authority can be marked inactive
by ISO {docnumber}/AG if the authority ceases to exist or
no longer wishes to register its written languages conversion systems.

Such inactive status shall be considered by the ISO {docnumber}/AG
upon request from the conversion system authority itself
or a member of the ISO {docnumber}/AG.

The ISO {docnumber}/AG at its sole discretion, will determine
what information will remain on the basis of practicality and
continuity of usage.


==== Modification of conversion system authority identifier

Modifications of an entry within the list of conversion system authority identifiers
shall be made upon the request of a member of ISO {docnumber}/AG
or the conversion system authority that manages the system.

The ISO {docnumber}/AG will decide upon the modification,
on the basis of the information received.

The previously assigned identifier will be reserved after modification for
backwards-compatibility purposes.


==== Modifications to information associated with identifiers

Modifications to a registered element shall be made upon requests from a member of the ISO {docnumber}/AG
or the conversion system authority that manages the system.

A significant change of name may require the ISO {docnumber}/AG to change the
identifier concerned.
The ISO {docnumber}/AG, however, shall endeavor to maintain stability in the
list of identifiers.


==== Inactive authorities

If a conversion system authority is marked inactive,
the responsibility of maintaining its written languages conversion system entries
are assumed by ISO {docnumber}/AG.


==== Varia authorities

The "`Varia systems`" conversion system authority is assigned
the identifier `Var`.
In this case, ISO {docnumber}/AG will manage
written languages conversion systems with need for representation but
which do not have a clear authority.

[example]
The Wade-Giles Chinese transcription system from <<ChineseWGS>> could be
represented as `Var:zho-Hani:Latn:WG-1912`.


[[authority-scs-codes]]
=== Operations on the list of written languages conversion systems and their codes


[[scs-alteration]]
==== Alterations to a written languages conversion system

Alterations to a registered element shall be made only upon
request of a member of ISO {docnumber}/AG
or the conversion system authority that manages the system.

A significant change of name may require the ISO {docnumber}/AG
to change the alpha code element concerned.
The ISO {docnumber}/AG, however, shall endeavor to maintain stability
in the list of code elements.


[[reservation]]
=== Reservation of code elements

==== Introduction

Some code elements managed by ISO {docnumber}/RA are reserved:

* for a limited period when their reservation is the result of
  the deprecation (<<scs-deprecation>>) or the alteration (<<scs-alteration>>)
  of an entry;

* for an indeterminate period when the reservation is the result of
  the application of international law or of
  exceptional requests (<<reservation-exceptional>>).

==== Period of non-allocation

Code elements that the ISO {docnumber}/AG has altered or deleted should not be reallocated indefinitely.


[[reservation-exceptional]]
==== Exceptional reservations

Code elements may be reserved, in exceptional cases,
for conversion systems authorities and written languages conversion systems
which the ISO {docnumber}/AG has decided not to include in the lists maintained
by ISO {docnumber}/RA,
but for which an interchange or encoding requirement exists.

==== Reallocation

Before reallocating a former code element or a formerly reserved code element,
the ISO {docnumber}/AG shall consult,
as appropriate, the authority or agency on whose behalf the code element was reserved,
and consideration shall be given to difficulties which might arise from the reallocation.


==== List of reserved code elements

A list of reserved code elements is kept by the ISO {docnumber}/RA.


=== Advice regarding use of code elements

The ISO {docnumber}/AG is available for consultation and assistance
on the use of codes for conversion system authorities and
written languages conversion systems.
