
[[AnnexA]]
[appendix]
== Registration

=== Registration authority (ISO {docnumber}/RA)

A registration authority (ISO {docnumber}/RA) has been appointed to
operate under guidelines provided in this Annex.

It has been entrusted with the following functions with regard to
the list of script conversion system authorities and script conversion
systems, together with code assignments and information associated with each entry:

. to add and eliminate these entries, in accordance with the rules in this document;

. to advise users and ISO member bodies regarding application of such information;

. to update and disseminate such information;

. to maintain a reference list of such information;

. to publish changes made to such information and the history of changes allowing traceability;

. to administer the reservation of the codes.

Changes to the content of the list of entries becomes effective
immediately upon publication.

The criteria provided in <<authority-scsa-codes>> to <<authority-scs-codes>>
shall be observed by the ISO {docnumber}/RA for changes to the list of
script conversion system authorities and script conversion
systems, their code assignments and associated information,
and for reservations of code elements.


=== Advisory group (ISO {docnumber}/AG)

An advisory group (ISO {docnumber}/AG) has been appointed to ensure
the operations of the registration authority (ISO {docnumber}/RA)
are in accordance with guidelines provided in this Annex.


[[authority-scsa-codes]]
=== Operations on list of script conversion system authorities and their codes


==== Registration of a new script conversion system authority

Additions to the list of script conversion system authority codes
shall be made on upon request from a member of the ISO {docnumber}/AG.

A script conversion system authority is eligible for registration
if it meets the requirements stated in <<scsa-requirements>>.

The proposer is responsible for providing justification to the
ISO {docnumber}/AG regarding the eligibility of such addition.

The ISO {docnumber}/AG will decide upon the addition, on the
basis of eligibility and usage justification.

Code elements will be allocated by the ISO {docnumber}/AG at its
discretion.


==== Marking a script conversion system authority inactive

A script conversion system authority can be marked inactive
by ISO {docnumber}/AG if the authority ceases to exist or
no longer wishes to register its script conversion systems.

Such inactive status shall be considered by the ISO {docnumber}/AG
upon request from the script conversion system authority itself
or a member of the ISO {docnumber}/AG.

The ISO {docnumber}/AG at its sole discretion, will determine
what information will remain on the basis of practicality and
continuity of usage.

If a script conversion system authority marked inactive,
the responsibility of maintaining its script conversion entries
are assumed by ISO {docnumber}/AG.


==== Modification of script conversion system authority code

Modifications of an entry within the list of script conversion system authority codes
shall be made upon the request of a member of ISO {docnumber}/AG.

The ISO {docnumber}/AG will decide upon the modification, on the basis of the information received.

The previously assigned code is reserved after modification for
backwards-compatibility purposes.


==== Modifications to information associated with codes

Modifications to a registered element shall be made upon requests from a member of the ISO {docnumber}/AG or
the script conversion system authority.

A significant change of name may require the ISO {docnumber}/AG to change the alpha code element concerned. The ISO {docnumber}/AG, however, shall endeavor to maintain stability in the list of code elements.



[[authority-scs-codes]]
=== Operations on list of script conversion systems and their codes


[[registration-adding-entry]]
==== Registration of a new script conversion system

Additions to the list of script conversion system codes shall be made on the basis of information from upon the request of a member of ISO {docnumber}/AG or the script conversion system authority that manages this system.

The ISO {docnumber}/AG will decide upon the addition, on the basis of the justification given for the actual requirements for international interchange. Code elements will be allocated accordingly.

A script conversion system is eligible for a script conversion system code assignment if it fulfills one of the following criteria:

* The system has been approved for official use at some level of government;

* The system has been developed and used by educational/scientific institutions, published in a peer reviewed scientific publication;

* The system has been in substantial usage.


Assigning of a script conversion system code also requires demonstration of one of the following usage factors:

* Necessity of identification of the system in interchange;
* Necessity of identification of the system in data encoding.

NOTE: Systems that are used in isolation or only for temporary usage does not need to be assigned codes.

////
Additions to the official and international time scale authorities require additional criteria:

* An official time scale authority must be endorsed by a body receiving direct authority by a member of the United Nations.
* An international time scale authority must be endorsed by an international standardization body in liaison with the ISO {docnumber}/AG.
////


[[scs-deletion]]
==== Deletion of a script conversion system

Deletion of a script conversion system codes shall be made upon
request of a member of ISO {docnumber}/AG
or the script conversion system authority that manages the system.

The ISO {docnumber}/AG will decide upon the deletion, on the basis
of the information received. The corresponding code element is reserved
for backwards-compatibility.


[[scs-alteration]]
==== Alterations to a script conversion system

Alterations to a registered element shall be made only upon
request of a member of ISO {docnumber}/AG
or the script conversion system authority that manages the system.

A significant change of name may require the ISO {docnumber}/AG
to change the alpha code element concerned.
The ISO {docnumber}/AG, however, shall endeavor to maintain stability
in the list of code elements.


[[reservation]]
=== Reservation of code elements

==== Introduction

Some code elements are reserved:

* for a limited period when their reservation is the result of
  the deletion (<<scs-deletion>>) or the alteration (<<scs-alteration>>)
  of an entry;

* for an indeterminate period when the reservation is the result of
  the application of international law or of
  exceptional requests (<<reservation-exceptional>>).

==== Period of non-allocation

Code elements that the ISO {docnumber}/AG has altered or deleted should not be reallocated during a period of at least ten years after the change.

The exact period is determined in each case on the basis of the extent to which the former code element was used.


[[reservation-exceptional]]
==== Exceptional reservations

Code elements may be reserved, in exceptional cases, for script conversion systems authorities and script conversion systems which the ISO {docnumber}/AG has decided not to include in the lists maintained by ISO {docnumber}/RA, but for which an interchange or encoding requirement exists.

==== Reallocation

Before reallocating a former code element or a formerly reserved code element, the ISO {docnumber}/AG shall consult, as appropriate, the authority or agency on whose behalf the code element was reserved, and consideration shall be given to difficulties which might arise from the reallocation.


==== List of reserved code elements

A list of reserved code elements is kept by the ISO {docnumber}/RA.


=== Advice regarding use of code elements

The ISO {docnumber}/AG is available for consultation and assistance on the use of codes for script conversion system authorities and script conversion systems.
