
== Transliteration codes

=== Structure of the alphabetic transliteration codes

The alphabetic script codes are created from the
original script name in the language commonly
used for it, transliterated or transcribed into Latin
letters. If a country, where the script concerned
has the status of a national script, requests a
certain script code, preference is given to this
code whenever possible. The four-letter codes
shall be written with an initial capital Latin letter
and final small Latin letters (taken from the range
Aaaa to Zzzz). This serves to help differentiate
script codes from language codes and country
codes: for example, Mong mon MON or M o n g
mn MN would refer to a book in the Mongolian
script, in the Mongolian language, originating in
Mongolia.

NOTE: See 4.7 regarding changes to the codes.


=== Structure of the numeric script codes

The numeric script codes have been assigned to
provide some measure of mnemonicity to the
codes used. The following ranges have been used:
000–099 Hieroglyphic and cuneiform scripts
100–199 Right-to-left alphabetic scripts
200–299 Left-to-right alphabetic scripts
300–399 Alphasyllabic scripts
400–499 Syllabic scripts
500–599 Ideographic scripts
600–699 Undeciphered scripts
700–799 (unassigned)
800–899 (unassigned)
900–999 Private use, aliases, special codes

NOTE: ISO/IEC 10646 uses the character-glyph model
(defined in ISO/IEC TR 15285:1998) to classify the
characters used to write different languages. ISO XXXXX
does not attempt to apply the character-glyph model,
because it is sometimes important to identify certain
script variants regardless of the encoding a given text
may employ. For example, a Syriac book may be written
in one of the three variants of the Syriac script
(Estrangelo, Eastern, Western). Identification of such
script variants, while outside the scope of
ISO/IEC 10646, is relevant to the content of script
codes. For example, a user ordering a book through
interlibrary loan may prefer, or may wish to exclude, the
Gaelic variant of the Latin script for reasons of ease of
legibility or familiarity with one of the variants.


NOTE: These classifications reflect the chief attribute
of the scripts so classified, and are not necessarily
comprehensive of the ways in which the scripts are
used. For example, while Ogham may be written from
left to right, it is also written vertically from bottom to top.
Similarly, the Hangul (Hangul, Hangeul) alphabet is
sometimes written in vertical columns, and the letters of
its alphabet are arranged in syllabic clusters.

NOTE: Within each category, numeric identifiers
assigned to scripts have followed a principle of
chronology, and genetic relationship, though this
principle cannot be established by any hard and fast
rule, since scripts may have many different characteristics.
Codes have been assigned by spacing them
out so that scripts encoded in future may be assigned to
appropriate places in the range.

=== Relation of the script codes to other ISO standards

The four-letter codes are derived from ISO 639-2
where the name of a script and the name of a
language using the script are identical (example:
Gujara¯tı¯ ISO 639 guj, ISO XXXXX Gujr). In cases
where there is no identity, the script name may
have a unique form.

[example]
Korean kor, Hangul (Hangu˘l, Hangeul)
Hang; Punjabi pan, Gurmukhı¯ Guru; Dhivehi div,
Thaana Thaa

Where possible, the first three letters of the fourletter
code corresponds to the three-letter code.
Preference is given to the Bibliographical codes
given in ISO 639-2 in deriving the codes specified
in this International Standard.

=== Adaptation of the script codes

When adapting this International Standard to other
scripts (for example Cyrillic or Greek), codes shall
be formed according to the principles of this
International Standard.


=== Addition of new script codes

For the purpose of allocating additional script
codes, ISO has designated a Maintenance Agency
for ISO XXXXX, the Unicode Consortium (Box
391476, Mountain View, CA 94039-1476, USA) as
the Registration Authority.

http://www.unicode.org/iso15924

ISO maintains a list of Maintenance Agencies and
Registration Authorities on the Internet at the
address

http://www.iso.ch/mara


The ISO list identifies the Registration Authority
and where the Registration Authority has
published materials related to this International
Standard on the Internet.



=== Application of script codes

Script codes can be used in the following
particular instances.

==== text

To indicate generally the scripts in which
documents are or have been written or recorded.

[source]
----
<META HTTP-EQUIV="Content-Language"
CONTENT="ga, ru">
<META NAME="Content-Script"
CONTENT="Latg, Cyrl">
----


==== text

To indicate the script specified in document
holding records (order records, bibliographic
records, etc.).

Examples:

— In bibliographies:
Röyte pomerantsen: Jewish folk humor. New York:
Schocken Books, 1965. xxvi, 203 p.; 20 cm. In
Yiddish (Latn) and English.
Kroatisch-Deutsch und Deutsch-Kroatisch: mit
einem Anhang der wichtigeren Neubildungen des
Kroatischen und Deutschen. Berlin: Axel Juncker,
1941. vi, 302, 314, 32 p.; 15 cm. In Croatian (Latn)
and German (Latf).
— In catalogue records:
Uniform Title: T i p it.aka. Suttapit.aka. Majjhimanika¯ya.
Hindi & Pali.
Title: S u t t a p it.ake Majjhimanika¯ y a pa¯ li =
Majjhima nika¯ya: Mu¯ l a p a r i ya¯ y avaggo,
Sı¯ h a na¯ davaggo ca, Hindı¯ -
a n u va¯dasahito / padha¯ n a s a m pa¯-
dako Sva¯mı¯ Dva¯rika¯da¯sas´a¯strı¯.
Edition: 1. sam. skaran. a
Published: Va¯ra¯ n. a sı¯: Bauddhabha¯r a tı¯, 1989-
<1993>
Description: 23 cm



Series: B a u d d h a b ha¯r a tı¯ g r a n t h a ma¯ la¯; 22-
<23-25>
LC Call No.: BQ1313.H5D93 1989
Notes: In Pali (Deva); introduction in
English and Hindi; translation in
Hindi. Theravada Buddhist canon.
1. Mu¯ l a p an. n. a s a k am. (3 v.) — 4.
Majjhimapan.n. a¯sakam. — 5. Uparipan.n.a¯sakam.
.
Language(s): hi, en, pi
Other authors: Dwarikadas Shastri, Swami
Other titles: Majjhima nika¯ya

==== To indicate the script used by an application.

Example:
“Laser Syriac: The fonts supplied in this package are
coded according to collection 85 of Annex A of
ISO/IEC 10646-1:2000 and provide a complete set
of glyphs in all three of the styles used to write
Syriac (Syre, Syrn, Syrj).”
4.7 Changes of script codes
In order to preserve the integrity of data coded
using the codes set forth in this International
Standard, it is intended that the four-letter and
numeric codes specified herein shall not be
changed unless there be extraordinarily
compelling reasons to do so.


