name: publish

on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/ubuntu.yml
      - .github/workflows/windows.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install yq
        env:
          VERSION: v4.9.1
          BINARY: yq_linux_amd64
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && \
            chmod +x /usr/bin/yq
      - name: Setup fonts
        run: |
          # We need to do this to install mscorefonts
          apt-add-repository -y contrib
          apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
          apt-get install -y ttf-mscorefonts-installer
          curl -Ls https://raw.githubusercontent.com/metanorma/vista-fonts-installer/master/vista-fonts-installer.sh | bash
      - name: Install gems from local Gemfile
        run: |
          curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/gemfile-to-bundle-add.sh | bash
      - name: Build document in the Metanorma container
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
          LANGUAGE: C.UTF-8
        run: |
          make
      - uses: actions/upload-artifact@master
        with:
          name: site
          path: site

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: site
    - name: Deploy to GH Pages
      env:
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        GH_PAGES_SOURCE: site
      run: |
        curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-to-gh-pages.sh | bash -s "${GH_PAGES_SOURCE}"
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 0
