name: publish

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - uses: actions/cache@v2
        with:
          path: ~/.fontist
          key: fontist-${{ runner.os }}
          restore-keys: fontist-${{ runner.os }}

      - uses: actions-mn/setup@master

      - run: metanorma site generate --agree-to-terms

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: site
          retention-days: 1

  deploy-gh-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - uses: actions/download-artifact@v2
        with:
          name: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./site
          force_orphan: true
          user_name: ${{ github.actor }}
          user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
          commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"
