name: publish

on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/ubuntu.yml
      - .github/workflows/windows.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@v2
      - name: Install gems from local Gemfile
        run: curl -L --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/gemfile-to-bundle-add.sh | bash
      - name: Build document in the Metanorma container
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
          LANGUAGE: C.UTF-8
        run: |
          make
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: site

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: site
        path: ${{ github.workspace }}/site
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
        user_name: ${{ github.actor }}
        user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
        commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 0
