name: publish

on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      - .github/workflows/macos.yml
      - .github/workflows/ubuntu.yml
      - .github/workflows/windows.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@master
      - name: Install gems from local Gemfile
        run: curl -L --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/gemfile-to-bundle-add.sh | bash
      - name: Build document in the Metanorma container
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
          LANGUAGE: C.UTF-8
        run: |
          make
      - uses: actions/upload-artifact@master
        with:
          name: results
          path: site

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: results
        path: ${{ github.workspace }}/site
    - name: Deploy to GH Pages
      env:
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        GH_PAGES_SOURCE: ${{ github.workspace }}/site
      run: |
        curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-to-gh-pages.sh | bash -s "${GH_PAGES_SOURCE}"
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 0
